version: "3"

volumes:
  expense_tracker_db_vol:

services:
  app:
    container_name: expense_tracker_app
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 5000:5000
    env_file: 
      - .env
    depends_on:
      - db
    restart: always


  db:
    container_name: expense_tracker_db_host
    image: mysql:5.7
    restart: always
    ports:
      - 32000:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: expense_tracker_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345678
    volumes:
      - expense_tracker_db_vol:/var/lib/mysql
